version: "3.8"

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24

services:
  app:
    build: ../seta-service
    ports:
      - "8080:8080"
    volumes:
      - ../seta-service/logs:/app/logs
    environment:
      - DATABASE_URL=postgres://huygdo@host.docker.internal:5432/seta_service_db?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monitoring

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=seta_user
      - POSTGRES_PASSWORD=seta_password
      - POSTGRES_DB=seta_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seta_user -d seta_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    working_dir: /loki
    networks:
      monitoring:
        ipv4_address: 172.16.238.10

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ../seta-service/logs:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.1.5
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - monitoring
    depends_on:
      - loki
volumes:
  loki-data:
  postgres_data:
